name: reusable workflow
on:
    push:
        branches:
            -main
    workflow_dispatch:

jobs:
    formatcode:
        uses: alsmk/CI-CD_tasks/.github/workflows/formatting.yml@main
        

        