name: reusable workflow
on:
    push:
        branches:
            -main
    workflow_dispatch:
# env:
#     TOKEN: ${{  secrets.TOKEN  }}
jobs:
    formatcode:
        uses: alsmk/CI-CD_tasks/.github/workflows/formatting.yml@main
    print_info:
        uses: alsmk/CI-CD_tasks/.github/workflows/printing_info.yml@main
        secrets:
            TOKEN: ${{ secrets.TOKEN  }}
    test:
        uses: alsmk/CI-CD_tasks/.github/workflows/testing.yml@main
        secrets:
            TOKEN: ${{  secrets.TOKEN  }}
      
        